# https://taskfile.dev

version: '3'

vars:
  REPO_NAME: go-yeet
  REPO_OWNER: davidalpert
  CMD_NAME: yeet
  CURRENT_VERSION:
    sh: sbot get version
  VERSION: '{{ .NEXT_VERSION | default .CURRENT_VERSION }}'
  GITBRANCH:
    sh: 'git rev-parse --abbrev-ref HEAD'
  GITCOMMITMESSAGE:
    sh: 'git log -1 --pretty=%s'
  GITDIRTY:
    sh: 'if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi'
  GITSHA:
    sh: 'git rev-parse --short HEAD'
  SEMVER: '{{.VERSION}}-{{.GITSHA}}{{ fromJson .GITDIRTY | ternary "+dirty" "" }}'

tasks:
  default:
    deps:
      - help
    silent: true

  cit:
    desc: CI task; cleans, run tests, and builds
    deps:
      - clean
      - vale
      - build
      - test

  clean:
    desc: clean built output
    cmds:
      - rm -rf ./bin

  doctor:
    desc: run doctor.sh to sort out development dependencies
    cmds:
      - ./.tools/doctor.sh

#  guard:
#    desc: run guard to watch
#    cmds:
#      - bundle exec guard

  gen:
    desc: run code-generation
    run: once
    vars:
      VERSION: "{{ .NEXT_VERSION | default .VERSION }}"
      SEMVER: "{{ .SEMVER }}"
    cmds:
      - task: gen:version

  gen:version:
    desc: updates the version
    run: once
    cmds:
      - echo "{{ .CMD_NAME }}" > ./internal/version/_APPNAME.txt
      - echo "{{ .VERSION }}" > ./internal/version/_APPVERSION.txt
      - echo "{{ .GITBRANCH }}" > ./internal/version/_GITBRANCH.txt
    vars:
      VERSION: "{{ .NEXT_VERSION | default .VERSION }}"
    status:
      - '[[ "{{ .CMD_NAME }}" == "$(cat ./internal/version/_APPNAME.txt)" ]]'
      - '[[ "{{ .VERSION }}" == "$(cat ./internal/version/_APPVERSION.txt)" ]]'
      - '[[ "{{ .GITBRANCH }}" == "$(cat ./internal/version/_GITBRANCH.txt)" ]]'

#  bundle:
#    desc: install ruby gems
#    run: once
#    cmds:
#      - bundle --quiet
  
  vale:
    desc: run linting rules against markdown files
    run: once
    cmds:
    - vale README.md CONTRIBUTING.md # we don't valedate CHANGELOG.md as that reflects historical commit summaries
    # TODO: run only when not in GITHUB_ACTIONS

  test:
    desc: run tests
    run: once
    deps:
      - gen
    cmds:
      - go test ./...
    silent: true

  autotest:
    desc: run tests continuously using goconvey's test UI
    deps:
      - gen
    cmds:
      - goconvey
    silent: true

#  features:
#    desc: run acceptance tests
#    deps:
#      - bundle
#      - gen
#      - test
#      - build
#    cmds:
#      - bundle exec cucumber --publish-quiet --tags 'not @wip' --tags 'not @ignore'
#
#  features-wip:
#    desc: run wip acceptance tests
#    deps:
#      - bundle
#      - gen
#      - test
#      - build
#    cmds:
#      - bundle exec cucumber --publish-quiet --tags '@wip' --tags 'not @ignore'

  build:
    desc: build
    run: once
    deps:
      - gen
      - test
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/{{ .CMD_NAME }} ./cmd/{{ .CMD_NAME }}

  changelog:
    desc: generate/update CHANGELOG.md
    cmds:
      - git-chglog --output CHANGELOG.md

  preview-release-notes:
    desc: preview release notes (generates RELEASE_NOTES.md)
    cmds:
      - git-chglog --output RELEASE_NOTES.md --template .chglog/RELEASE_NOTES.tpl.md "v{{ .VERSION }}"

  release:
    cmds:
      - task: gen
        vars:
          VERSION: "{{ .NEXT_VERSION }}"
      # - task: features
      - git add -f internal/version/detail.go
      - git-chglog --next-tag v{{ .NEXT_VERSION }} --output CHANGELOG.md
      - git add -f CHANGELOG.md
      - git commit --message "release notes for v{{ .NEXT_VERSION }}"
      - sbot release version --mode {{ .BUMP_TYPE }}
      - git show --no-patch --format=short v{{ .NEXT_VERSION }}
    preconditions:
      - sh: git diff-files --quiet
        msg: There are unstaged changes; clean your working directory before releasing.
      - sh: git diff-index --quiet --cached HEAD --
        msg: There are uncomitted changes; clean your working directory before releasing.
    vars:
      NEXT_VERSION:
        sh: sbot predict version --mode {{ .BUMP_TYPE }}
    
  release-patch:
    desc: release a patch update
    cmds:
      - task: release
        vars:
          BUMP_TYPE: patch

  release-minor:
    desc: release a minor update
    cmds:
      - task: release
        vars:
          BUMP_TYPE: minor

  release-major:
    desc: release a major update
    cmds:
      - task: release
        vars:
          BUMP_TYPE: major

  help:
    desc: list targets
    cmds:
      - echo "{{ .CMD_NAME}} v{{ .VERSION }}"
      - echo ""
      - task --list
    silent: true

