name: Pull Request Feedback

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
    - main

permissions:
  contents: read
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4

    - name: Install dependencies
      run: |
        go install github.com/restechnica/semverbot/cmd/sbot@latest
        asdf reshim golang

    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

    - name: Vale Linter # https://github.com/marketplace/actions/vale-linter
      uses: errata-ai/vale-action@v2.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        fail_on_error: true
        files: '["README.md", "CONTRIBUTING.md"]'
        filter_mode: nofilter
        reporter: github-pr-check
        version: 3.9.6

    - name: Validate build dependencies
      run: |
        ./.tools/doctor.sh
      continue-on-error: false

    - name: Unit tests
      run: |
        task test
      continue-on-error: false

    # - name: "Features"
    #   env:
    #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     task features | reviewdog -name=features -fail-on-error=true -efm="cucumber %f:%l # Scenario: %m" -diff="git diff FETCH_HEAD" -filter-mode=nofilter -reporter=github-pr-check -tee
    #   continue-on-error: false
